### ISSUE TITLE
setActorModel not working

### ISSUE THREAD

**Issue by goshante** [Asiern/ReplicantHook#5]
Your setActorModel not working at all, i tried a lot of ways to test it.
Infinite magic and other - works fine.
I tried to set model before game loads, after game loaded and even during loading, after setting model just was running between zones multiple times and after map was loaded my hero still has child version of brother Nier.
I changed nothing in your project, just compiled is as it is. And other features are workig!
Am i doing something wrong or your function has wrong offset or something? Do I have to complete the game to get this working?

**Comment by Asiern** [comment]
I have tried it out with different save files and it seems like you need to, at least, complete the A ending for this to work.

**Comment by goshante** [comment]
> 
> 
> I have tried it out with different save files and it seems like you need to, at least, complete the A ending for this to work.

Got it. 
Well, going to find some other way to change player model without beating the game.
